import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_eighteen_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_twenty_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_ninteen_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_seventeen_texts.dart';
import '../get_pages_texts/elm_21/get_page_twenty_five_texts.dart';
import '../get_pages_texts/elm_21/get_page_twenty_four_texts.dart';
import '../get_pages_texts/elm_21/get_page_twenty_one_texts.dart';
import '../get_pages_texts/elm_21/get_page_twenty_seven_texts.dart';
import '../get_pages_texts/elm_21/get_page_twenty_six_texts.dart';
import '../get_pages_texts/elm_21/get_page_twenty_three_texts.dart';
import '../get_pages_texts/elm_21/get_page_twenty_two_texts.dart';
import '../get_pages_texts/elm_21/get_page_therty_one_texts.dart';
import '../get_pages_texts/elm_21/get_page_therty_two_texts.dart';
import '../get_pages_texts/elm_21/get_page_therty_three_texts.dart';
import '../get_pages_texts/elm_21/get_page_therty_Four_texts.dart';
import '../get_pages_texts/elm_21/get_page_therty_Five_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_eleven_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_fourteen_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_sixteen_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_therteen_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_therty_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_twelve_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_fifteen_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_twenty_eight_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_twenty_nine_texts.dart';
import 'package:flutter/material.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_five_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_four_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_one_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_seven_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_six_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_three_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_two_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_eight_texts.dart';
import 'package:elm/view/widget/custom_text_slider/get_pages_texts/elm_21/get_page_nine_texts.dart';
import '../get_pages_texts/elm_21/get_page_ten_texts.dart';

List<TextSpan> whichPageToGetInElm21(int i) {
  switch (i) {
    case 0:
      return getPageOneTexts(i);
    case 1:
      return getPageTwoTexts(i);
    case 2:
      return getPageThreeTexts(i);
    case 3:
      return getPageFourTexts(i);
    case 4:
      return getPageFiveTexts(i);
    case 5:
      return getPageSixTexts(i);
    case 6:
      return getPageSevenTexts(i);
    case 7:
      return getPageEightTexts(i);
    case 8:
      return getPageNineTexts(i);
    case 9:
      return getPageTenTexts(i);
    case 10:
      return getPageElevenTexts(i);
    case 11:
      return getPageTwelveTexts(i);
    case 12:
      return getPageTherteenTexts(i);
    case 13:
      return getPageFourteenTexts(i);
    case 14:
      return getPageFifteenTexts(i);
    case 15:
      return getPageSixteenTexts(i);
    case 16:
      return getPageSeventeenTexts(i);
    case 17:
      return getPageEighteenTexts(i);
    case 18:
      return getPageNinteenTexts(i);
    case 19:
      return getPageTwentyTexts(i);
    case 20:
      return getPageTwentyOneTexts(i);
    case 21:
      return getPageTwentyTwoTexts(i);
    case 22:
      return getPageTwentyThreeTexts(i);
    case 23:
      return getPageTwentyFourTexts(i);
    case 24:
      return getPageTwentyFiveTexts(i);
    case 25:
      return getPageTwentySixTexts(i);
    case 26:
      return getPageTwentySevenTexts(i);
    case 27:
      return getPageTwentyEightTexts(i);
    case 28:
      return getPageTwentyNineTexts(i);
    case 29:
      return getPageThertyTexts(i);
    case 30:
      return getPageThertyOneTexts(i);
    case 31:
      return getPageThertyTwoTexts(i);
    case 32:
      return getPageThertyThreeTexts(i);
    case 33:
      return getPageThertyFourTexts(i);
    case 34:
      return getPageThertyFiveTexts(i);

    default:
      return [];
  }
}
